variables:
  GIT_CLEAN_FLAGS: "none"
stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Building the project..."

test:
  stage: test
  script:
    - echo "Running tests..."

deploy:
  stage: deploy
  script:
    - echo "Deploying the project..."
    - cd /var/www/pillstore.app/html/admin-backend
    - sudo git pull -p ssh://git@git.90-soft.com:2200/rayanazzam/pill-store-landlord-backend.git development
    - sudo php artisan migrate
    - sudo php artisan optimize:clear
    - sudo chmod -R 777 /var/www/pillstore.app/html/admin-backend/storage
    - sudo chmod -R 777 /var/www/pillstore.app/html/admin-backend/bootstrap
